### ISSUE TITLE
Failed to backup measurements with "/" in name

### ISSUE THREAD

**Issue by anpryl** [Quiq/influxdb-tools#3]
```sh
$ ./influx-backup.py --url http://localhost:8086 --dump-db k8s --dir backup --user admin --dump
Password:
>> 2018-04-18 20:07:48 UTC
Starting backup of "k8s" db to "backup" dir

Measurements:
['cpu/limit', 'cpu/node_allocatable', 'cpu/node_capacity', 'cpu/node_reservation', 'cpu/node_utilization', 'cpu/request', 'cpu/usage', 'cpu/usage_rate', 'cpu_usage_1d', 'filesystem/inodes', 'filesystem/inodes_free', 'filesystem/limit', 'filesystem/usage', 'ingress/access-log', 'memory/cache', 'memory/limit', 'memory/major_page_faults', 'memory/major_page_faults_rate', 'memory/node_allocatable', 'memory/node_capacity', 'memory/node_reservation', 'memory/node_utilization', 'memory/page_faults', 'memory/page_faults_rate', 'memory/request', 'memory/rss', 'memory/usage', 'memory/working_set', 'memory_usage_1d', 'network/rx', 'network/rx_errors', 'network/rx_errors_rate', 'network/rx_rate', 'network/tx', 'network/tx_errors', 'network/tx_errors_rate', 'network/tx_rate', 'uptime']

Measurement fields:
{'network/tx_errors_rate': {'value': 'float'}, 'memory/limit': {'value': 'integer'}, 'memory/node_utilization': {'value': 'float'}, 'memory/request': {'value': 'integer'}, 'memory/page_faults_rate': {'value': 'float'}, 'cpu/limit': {'value': 'integer'}, 'cpu/node_utilization': {'value': 'float'}, 'network/tx_rate': {'value': 'float'}, 'network/tx': {'value': 'integer'}, 'memory/cache': {'value': 'integer'}, 'memory/node_capacity': {'value': 'float'}, 'network/tx_errors': {'value': 'integer'}, 'uptime': {'value': 'integer'}, 'cpu/node_capacity': {'value': 'float'}, 'cpu/request': {'value': 'integer'}, 'filesystem/usage': {'value': 'integer'}, 'cpu/node_reservation': {'value': 'float'}, 'cpu/node_allocatable': {'value': 'float'}, 'memory/node_allocatable': {'value': 'float'}, 'ingress/access-log': {'request_size': 'float', 'browser_version': 'string', 'browser_name': 'string', 'client_addr': 'string', 'response_size': 'float', 'host': 'string', 'engine_name': 'string', 'container_name': 'string', 'client_os': 'string', 'duration': 'float', 'is_bot': 'boolean', 'client_platform': 'string', 'scheme': 'string', 'is_mobile': 'boolean', 'labels': 'string', 'client_port': 'float', 'engine_version': 'string', 'namespace_name': 'string'}, 'filesystem/inodes': {'value': 'integer'}, 'network/rx_errors_rate': {'value': 'float'}, 'memory/usage': {'value': 'integer'}, 'network/rx': {'value': 'integer'}, 'filesystem/limit': {'value': 'integer'}, 'memory/node_reservation': {'value': 'float'}, 'cpu/usage_rate': {'value': 'integer'}, 'cpu/usage': {'value': 'integer'}, 'network/rx_errors': {'value': 'integer'}, 'memory/major_page_faults': {'value': 'integer'}, 'network/rx_rate': {'value': 'float'}, 'memory/working_set': {'value': 'integer'}, 'filesystem/inodes_free': {'value': 'integer'}, 'memory/major_page_faults_rate': {'value': 'float'}, 'memory/rss': {'value': 'integer'}, 'memory/page_faults': {'value': 'integer'}}

Dumping cpu/limit...Traceback (most recent call last):
  File "./influx-backup.py", line 320, in <module>
    dump(args.dump_db, WHERE)
  File "./influx-backup.py", line 148, in dump
    f = open('%s/%s' % (DIR, m), 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'backup/cpu/limit'
```

**Comment by roman-vynar** [comment]
Thanks for reporting, I guess it can be fixed by escaping `/` in the path to files.

**Comment by roman-vynar** [comment]
Fixed by https://github.com/Quiq/influxdb-tools/commit/3789263524dd9cd23a78203e4957c932c93c8b6f
